name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: DPJ Backend
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: DPJ Backend
      run: docker build -t Iclimbs/DPJ_Backend .
    - name: Push to Dockerhub
      run: docker push Iclimbs/DPJ_Backend:latest
